import iFactors as ifact
int = input('Tell me the interest rate you have in mind (%): ')
int = float(int)
num = input('How about the number of period? ')
num = float(num)
print("The interest factor for ",int,'% over ',num, " are as follow:\n")
print('F given P factor: ', ifact.fpd(int,num),'\n')
print('P given F factor: ', ifact.pfd(int,num),'\n')
print('F given A factor: ', ifact.fad(int,num),'\n')
print('P given A factor: ', ifact.pad(int,num),'\n')
print('A given F factor: ', ifact.afd(int,num),'\n')
print('A given P factor: ', ifact.apd(int,num),'\n')
print('P given G factor: ', ifact.pgd(int,num),'\n')
print('A given G factor: ', ifact.agd(int,num),'\n')
print('\n Continuous Compounding; Discrete payments\n')
print('F given P factor: ', ifact.fpc(int,num),'\n')
print('P given F factor: ', ifact.pfc(int,num),'\n')
print('F given A factor: ', ifact.fac(int,num),'\n')
print('A given F factor: ', ifact.afc(int,num),'\n')
print('P given A factor: ', ifact.pac(int,num),'\n')
print('A given P factor: ', ifact.apc(int,num),'\n')
print('A given G factor: ', ifact.agc(int,num),'\n')
